### ISSUE TITLE
Error: missing security-assets directory

### ISSUE THREAD

**Issue by meaderick** [mortendj/ayfieExpress#1]
Hi Morten, this is Meade Goolrick with ONE Discovery, Inc.

Today I was doing an Ayfie 2.5.0 installation using ayfieExpress and ran into the subject problem. I have attached 2 files:

1. ayfieExpress-error.txt has shell input and output with some comments.
2. ayfeExpress.log is the generated log file.

I was able to easily complete the installation since the 2.5.0 zip file had been downloaded prior to the error. Wanted to alert you.
[ayfieExpress-error.txt](https://github.com/mortendj/ayfieExpress/files/4404409/ayfieExpress-error.txt)
[ayfieExpress.log](https://github.com/mortendj/ayfieExpress/files/4404410/ayfieExpress.log)

**Comment by mortendj** [comment]
Hi Meade, I fixed it, try again with the latest version of the code.

Regards,
Morten

**Comment by meaderick** [comment]
Morten,

I used the latest version to install ayfie 2.5.0 yesterday and it worked flawlessly. Console messages:

> /home/ayfie# sudo python3 ayfieExpress.py config.json
> Preparing user and host...
> Docker already installed...
> Installing docker-compose...
> Starting docker...
> Downloading and unzipping installer...
> Adding custom files (if any)...
> Making scripts executable...
> Starting the Inspector - downloading any required Docker images not already downloaded. This could take many minutes...
> Docker image download (if any) completed. Now waiting for Elasticsearch to come up
> The ayfie Inspector is now up and ready
> 

Thanks for the fix, it makes my life easier. 👍
